# Generated by Django 5.0 on 2024-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video_file_480p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video_file_720p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video_file_1080p', models.FileField(blank=True, null=True, upload_to='videos')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
