# Generated by Django 5.0.1 on 2024-01-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmography', '0005_alter_filmography_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmography',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Documentary', 'Documentary'), ('Animation', 'Animation'), ('Horror', 'Horror')], default='', max_length=50),
        ),
    ]
